//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace adsincidencias.entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string usrNombre { get; set; }
        public string usrCorreo { get; set; }
        public string usrNombreUsusario { get; set; }
        public string usrContrasena { get; set; }
        public int usrEmpresaID { get; set; }
        public string usrApPaterno { get; set; }
        public string usrApMaterno { get; set; }
    
        public virtual Empresa Empresas { get; set; }
    }
}
